name: Assets

on:
  release:
    types: [published]

jobs:
  build:
    name: Upload Assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create zip
        run: |
          cd custom_components/volkswagencarnet
          zip volkswagencarnet.zip -r ./

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./custom_components/volkswagencarnet/volkswagencarnet.zip
          asset_name: volkswagencarnet.zip
          tag: ${{ github.ref }}
          overwrite: true