name: Publish

on:
  push:
    branches:
      - masterrr

jobs:
  build:
    name: Publish New Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.23.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true