name: "Validate"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validate-hassfest:
    name: With hassfest
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master

  validate-hacs:
    name: With HACS action
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: HACS Validation
        uses: hacs/action@main
        with:
          category: integration
          comment: True

  validate-labels:
    name: With PR label action
    runs-on: ubuntu-latest
    steps:
      - name: Verify PR labels
        uses: jesusvasquez333/verify-pr-label-action@v1.3.1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          valid-labels: 'bug, enhancement'
          invalid-labels: 'help wanted, invalid, question'
          pull-request-number: '${{ github.event.pull_request.number }}'

        
        

      # - uses: actions/setup-python@v2
      #   name: Setup Python

      # - uses: actions/cache@v2
      #   name: PIP Cache
      #   with:
      #     path: |
      #       ~/.cache/pip
      #     key: custom-component-ci

      # - uses: hacs/action@main
      #   name: HACS Validation
      #   with:
      #     CATEGORY: integration

      # - uses: home-assistant/actions/hassfest@master
      #   name: Hassfest Validation
